openapi: 3.0.0

info:
  title: Todo app OAS
  description: OpenApi specification for a todo application
  version: 1.0.0

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int32
        user:
          type: string
          format: uuid
        task:
          type: string
        status:
          $ref: '#/components/schemas/Status'
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
      required:
        - user
        - task
        - status
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    User:
      type: string
      format: uuid
    Status:
      type: string
      enum:
        - on_hold
        - working
        - done
paths: {}
